<?php
// ============================================================================
// SECTION 0: DEFENSE-READY COMMENTING CONTEXT
// Purpose: verify_email.php completes the UTMSPACE Staff registration workflow.
// The following comments explain what each block performs and why email
// verification protects authentication, user identity, and claim-system access.
// ============================================================================

// SECTION: SESSION INITIALIZATION - Starts or resumes the browser session so verified users can be redirected consistently.
session_start();

// SECTION: DEPENDENCY LOADING - Loads the shared database connection used by the authentication workflow.
require_once "db.php";

$page_title = 'Email Verification';
$message_title = 'Verification Failed';
$message_body = 'The verification link is invalid or has expired.';
$message_type = 'error';
$show_login_link = false;

// === SECTION 1: VERIFICATION TOKEN INPUT ===
// What: Read the token from the verification link sent to the user's email address.
// Why: The token proves that the user has access to the email inbox used during registration.
$token = trim($_GET['token'] ?? '');

// SECURITY: Rejecting malformed tokens prevents unnecessary database lookups and limits token probing.
// Why: Verification tokens are expected to be 64 lowercase hexadecimal characters generated by random_bytes().
if ($token === '' || !preg_match('/^[a-f0-9]{64}$/', $token)) {
    $message_body = 'Please use the full verification link from your email.';
} else {
    // === SECTION 2: TOKEN LOOKUP ===
    // What: Locate the user account that owns the submitted verification token.
    // Why: Only the matching pending account should be eligible for email verification.
    // SECURITY: Preventing SQL Injection with a prepared statement and bind_param().
    $stmt = $conn->prepare("SELECT id, name, email_verified, email_verification_expires_at FROM users WHERE email_verification_token = ? LIMIT 1");
    $stmt->bind_param("s", $token);
    $stmt->execute();
    $result = $stmt->get_result();
    $user = $result->fetch_assoc();
    $stmt->close();

    if (!$user) {
        $message_body = 'This verification link is invalid or has already been used.';
    } elseif ((int) $user['email_verified'] === 1) {
        $message_title = 'Already Verified';
        $message_body = 'Your email address has already been verified. You may log in now.';
        $message_type = 'info';
        $show_login_link = true;
    } elseif (strtotime($user['email_verification_expires_at']) < time()) {
        $message_body = 'This verification link has expired. Please contact Admin or register again.';
    } else {
        // === SECTION 3: ACCOUNT VERIFICATION UPDATE ===
        // What: Mark the account as verified and clear the single-use verification token.
        // Why: Verified accounts can log in, while clearing the token prevents replay of the same email link.
        // SECURITY: Preventing SQL Injection with a prepared statement and bind_param().
        $verified = 1;
        $user_id = (int) $user['id'];
        $update = $conn->prepare("UPDATE users SET email_verified = ?, email_verification_token = NULL, email_verification_expires_at = NULL WHERE id = ?");
        $update->bind_param("ii", $verified, $user_id);

        if ($update->execute()) {
            $message_title = 'Email Verified';
            $message_body = 'Your email address has been verified successfully. You may log in to the UTMSPACE Claim System.';
            $message_type = 'success';
            $show_login_link = true;
        }
        $update->close();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<!-- SECTION: DOCUMENT METADATA - Loads responsive settings and external UI libraries required by this verification page. -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($page_title, ENT_QUOTES, 'UTF-8'); ?> - UTMSPACE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        /* SECTION: PAGE FOUNDATION - Provides a clean institutional verification screen for account activation. */
        body {
            min-height: 100vh;
            background: linear-gradient(135deg, #0B3B5E 0%, #123f63 100%);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 24px;
        }

        /* SECTION: CARD/PANEL COMPONENT - Groups the verification result and next action in one readable panel. */
        .verification-card {
            width: 100%;
            max-width: 520px;
            background: #ffffff;
            border-radius: 22px;
            padding: 34px;
            box-shadow: 0 24px 50px rgba(0, 0, 0, 0.25);
            text-align: center;
        }

        .verification-icon {
            width: 72px;
            height: 72px;
            border-radius: 50%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 18px;
            background: #e0f2fe;
            color: #0B3B5E;
            font-size: 30px;
        }

        .btn-primary-custom {
            background: #0B3B5E;
            color: #ffffff;
            border: none;
            border-radius: 999px;
            padding: 11px 22px;
            font-weight: 700;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            justify-content: center;
        }

        .btn-primary-custom:hover {
            background: #C1272D;
            color: #ffffff;
        }
    </style>
</head>
<!-- SECTION: PAGE BODY - Presents the verification outcome to the registering Staff user. -->
<body>
    <main class="verification-card">
        <div class="verification-icon">
            <i class="fas <?php echo $message_type === 'success' ? 'fa-check' : ($message_type === 'info' ? 'fa-info' : 'fa-times'); ?>"></i>
        </div>
        <!-- SECURITY: Preventing XSS by escaping verification result text before rendering. -->
        <h3 class="fw-bold mb-3" style="color:#0B3B5E;"><?php echo htmlspecialchars($message_title, ENT_QUOTES, 'UTF-8'); ?></h3>
        <!-- SECURITY: Preventing XSS by escaping verification result text before rendering. -->
        <p class="text-muted mb-4"><?php echo htmlspecialchars($message_body, ENT_QUOTES, 'UTF-8'); ?></p>

        <?php if ($show_login_link): ?>
            <a href="login.php" class="btn-primary-custom">
                <i class="fas fa-sign-in-alt me-2"></i>Go to Login
            </a>
        <?php else: ?>
            <a href="register.php" class="btn-primary-custom">
                <i class="fas fa-user-plus me-2"></i>Back to Registration
            </a>
        <?php endif; ?>
    </main>
</body>
</html>
